<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="4.1.1" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.3.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.3.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
    <PackageVersion Include="YoloDotNet" Version="4.2.0" />
    <PackageVersion Include="YoloDotNet.ExecutionProvider.Cpu" Version="1.1.0" />
  </ItemGroup>
</Project>