<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="YoloDotNet" />
    <PackageReference Include="YoloDotNet.ExecutionProvider.Cpu" />
  </ItemGroup>

</Project>
